/* Dot One Media — site media config.
   Generated by the Asset Portal on 2026-07-08.
   Replace this file in the repo to update every image & video on dot1.media. */
window.SITE_ASSETS = {
  "logoNav": "images/DotOneMediaLogoAnimation.gif",
  "logoContact": "images/GreyTPLogoAnimated.gif",
  "logoFooter": "images/BLKFullTPLogo.png",
  "hero": "images/BASEcamp.jpg",
  "purposeImage": "images/mountian.jpg",
  "work1": "images/tngimg_1.1.1.png",
  "work2": "images/gandg.jpg",
  "work2Youtube": "ZWZ4mo51cnc",
  "work4": "images/camera.png",
  "youtubeId": "zMpii5i4c0s",
  "appIcon": "images/D1N.png",
  "appStoreBadge": "images/AppStore.png",
  "screen1": "images/01.png",
  "screen2": "images/02.png",
  "screen3": "images/03.png",
  "teamDennis": "images/Zaddy.jpeg",
  "teamBrittany": "images/brittany.jpeg",
  "bookCover": "images/TheopoetecologyCover.png",
  "acuityUrl": "https://dotonemedia.as.me/",
  "photos": [
    {
      "url": "images/maternity.jpg",
      "caption": "Maternity — Alaska"
    },
    {
      "url": "images/Familysession.jpg",
      "caption": "Family session"
    },
    {
      "url": "images/wedding.jpg",
      "caption": "Portrait"
    },
    {
      "url": "images/NeffFamily.jpg",
      "caption": "Family session"
    },
    {
      "url": "FloodFamily.jpg",
      "caption": "Family session"
    },
    {
      "url": "images/NeffFamily2.jpg",
      "caption": "Family session"
    },
    {
      "url": "images/AlexMotherDayMini.jpg",
      "caption": "Mother's Day mini"
    },
    {
      "url": "images/SeniorMini.jpg",
      "caption": "Senior session"
    }
  ]
};
